spring:
  datasource:
    url: jdbc:mysql://NEW_DB_HOST:3306/edupilot
    username: NEW_DB_USER
    password: NEW_DB_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
    legacy:
      url: jdbc:mysql://LEGACY_DB_HOST:3306/legacy_db
      username: LEGACY_DB_USER
      password: LEGACY_DB_PASSWORD
      driver-class-name: com.mysql.cj.jdbc.Driver
